### ISSUE TITLE
Can not access "Goals Screen"

### ISSUE THREAD

**Issue by nepal2030** [OfficeDev/microsoft-teams-apps-goaltracker#15]
I completed deployment for “Goal Tracker” app for MS teams. Then after I upload MS Teams admin center and gave all permission to access. When I am testing on MS Teams, “Set goals” appears in a second then ask always “sign in” after completed "sign in", again appears in a second “Set Goal” screen then again “sing-in”. Briefly, I can not start "Set Goal"

![image](https://user-images.githubusercontent.com/59321028/109144666-beb50700-7761-11eb-86c0-451cf7fff854.png)
![image](https://user-images.githubusercontent.com/59321028/109144676-c2e12480-7761-11eb-9e81-d37d776f96a8.png)

Could you help to solve this issue, please ?

**Comment by v-smahaj** [comment]
@nepal2030 We are not able to repro this issue at our end. 
Let us know if this issue still persists.
